# Generated by Django 3.2.7 on 2021-10-02 10:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('board', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Submit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64)),
                ('student_number', models.PositiveIntegerField()),
                ('state', models.CharField(choices=[('SU', 'Running'), ('RU', 'Running'), ('AC', 'Accepted'), ('RE', 'Rejected'), ('DE', 'Deleted')], default='SU', max_length=2)),
                ('type', models.CharField(choices=[('T', 'Trie'), ('H', 'Hashtable')], max_length=1)),
                ('staff', models.BooleanField(default=False)),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('submission', models.FileField(upload_to='')),
            ],
        ),
    ]
