# Generated by Django 3.2.7 on 2021-10-02 10:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('board', '0003_submit_time'),
    ]

    operations = [
        migrations.AddField(
            model_name='submit',
            name='ip',
            field=models.GenericIPAddressField(default='0.0.0.0', protocol='IPv4'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='submit',
            name='time_check',
            field=models.FloatField(null=True),
        ),
        migrations.AddField(
            model_name='submit',
            name='time_load',
            field=models.FloatField(null=True),
        ),
        migrations.AddField(
            model_name='submit',
            name='time_size',
            field=models.FloatField(null=True),
        ),
        migrations.AddField(
            model_name='submit',
            name='time_unload',
            field=models.FloatField(null=True),
        ),
        migrations.AlterField(
            model_name='submit',
            name='time',
            field=models.FloatField(null=True),
        ),
    ]
