# Generated by Django 3.2.7 on 2021-10-04 08:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('board', '0004_auto_20211002_1056'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Submit',
            new_name='Submission',
        ),
    ]
