# Generated by Django 3.2.7 on 2021-10-13 19:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('board', '0006_auto_20211005_2313'),
    ]

    operations = [
        migrations.CreateModel(
            name='Dictionary',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=16, unique=True, verbose_name='Name')),
                ('file', models.FileField(upload_to='dictionaries', verbose_name='File')),
            ],
        ),
        migrations.CreateModel(
            name='Text',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=16, unique=True, verbose_name='Name')),
                ('file', models.FileField(upload_to='texts', verbose_name='File')),
            ],
        ),
        migrations.AlterField(
            model_name='submission',
            name='submission',
            field=models.FileField(upload_to='submissions', verbose_name='Submission'),
        ),
    ]
