# Generated by Django 3.2.8 on 2021-10-13 21:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('board', '0009_alter_submission_type'),
    ]

    operations = [
        migrations.CreateModel(
            name='SiteConfigurations',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('standard_board', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='board.board')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
