# Generated by Django 3.2.8 on 2021-10-13 21:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('board', '0010_siteconfigurations'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='siteconfigurations',
            options={'verbose_name': 'Site Configuration'},
        ),
        migrations.AlterField(
            model_name='siteconfigurations',
            name='standard_board',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='board.board', verbose_name='Standard Board'),
        ),
        migrations.AlterField(
            model_name='submission',
            name='type',
            field=models.CharField(choices=[('T', 'Trie'), ('H', 'Hashtable'), ('O', 'Other')], default='H', max_length=1, verbose_name='Data structure'),
        ),
    ]
